config/routes.rb
Rails.application.routes.draw do
  
  resources :categories
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :bookmarks
  post '/categoria', to: 'categories#create', as: "create_category"
  get '/categories.json', to: 'categories#get_api', as: 'get_api'
  # resources :bookmarks do
  #   resources :types, only: [:show]
  # end
  # resources :types, except: [:show]
  root 'bookmarks#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
    has_many :categories, dependent: :delete_all
    enum status: [:Privado, :Publico]
    validates :status, presence: true
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :bookmark
  belongs_to :kind
  belongs_to :subcategory
end

app/models/kind.rb
class Kind < ApplicationRecord
    has_many :categories
end

app/models/subcategory.rb
class Subcategory < ApplicationRecord
    has_many :categories
end

app/models/type.rb
class Type < ApplicationRecord
    belongs_to :bookmark, optional: true

    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_bookmark, only: [:show, :edit, :update, :destroy]

  # GET /bookmarks
  # GET /bookmarks.json
  def index
    @bookmark = Bookmark.new
    @categories = Category.all
    @kinds = Kind.all
    @category = Category.new
    @q = Bookmark.ransack(params[:q])
    @bookmarks = @q.result(distinct: true)
    @subcategories = Subcategory.all
    @types_graphic = Kind.group(:name).count()
    @bookmarks_graphic = Kind.group(:name).count()
  end

  # def get_api
  #   @bookmarks = Bookmark.all
  #   render json: @bookmarks
  # end

  # GET /bookmarks/1
  # GET /bookmarks/1.json
  def show
  end

  # GET /bookmarks/new
  def new
    @bookmark = Bookmark.new
  end

  # GET /bookmarks/1/edit
  def edit
  end

  # POST /bookmarks
  # POST /bookmarks.json
  def create
    @bookmark = Bookmark.new(bookmark_params)

    respond_to do |format|
      if @bookmark.save
        format.html { redirect_to @bookmark, notice: 'El marcador fue creado con exito.' }
        format.js { @bookmark }
      else
        format.html { render :new }
        format.js { render :index }
      end
    end
  end

  # PATCH/PUT /bookmarks/1
  # PATCH/PUT /bookmarks/1.json
  def update
    respond_to do |format|
      if @bookmark.update(bookmark_params)
        format.html { redirect_to @bookmark, notice: 'Bookmark was successfully updated.' }
        format.js { @bookmark }
      else
        format.html { render :edit }
        format.js { render :index }
      end
    end
  end

  # DELETE /bookmarks/1
  # DELETE /bookmarks/1.json
  def destroy
    @bookmark.destroy
    respond_to do |format|
      format.html { redirect_to bookmarks_url, notice: 'Bookmark was successfully destroyed.' }
      format.js { @bookmark }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bookmark
      @bookmark = Bookmark.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def bookmark_params
      params.require(:bookmark).permit(:url, :status)
    end
    def type_params
      params.require(:type).permit(:theme, :link, :bookmark_id)
    end
    # def select_bookmark
    #   @bookmark_find = Bookmark.all.pluck(:category, :id)
    # end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  def get_api
    @categories = Category.all
    render json: @categories
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:name, :subcategory_id, :bookmark_id, :kind_id)
    end

    def select_bookmark
      @bookmark = Bookmark.all.pluck(:category, :id)
    end

    def select_bookmark
      @kind = Kind.all.pluck(:name, :id)
    end

    def select_subcategory
      @kind = Subcategory.all.pluck(:name, :id)
    end
end

app/controllers/types_controller.rb
class TypesController < ApplicationController
  before_action :set_type, only: [:show, :edit, :update, :destroy]
  before_action :select_bookmark, only: [:new, :edit]
  # GET /types
  # GET /types.json
  def index
    @types = Type.all
  end

  # GET /types/1
  # GET /types/1.json
  def show
  end

  def get_api
    @types = Type.all
    render json: @types
  end

  # GET /types/new
  def new
    @type = Type.new
  end

  # GET /types/1/edit
  def edit
  end

  # POST /types
  # POST /types.json
  def create
    @type = Type.new(type_params)

    respond_to do |format|
      if @type.save
        format.html { redirect_to @type, notice: 'Type was successfully created.' }
        format.js { @type }
      else
        format.html { render :new }
        format.js { render :index }
      end
    end
  end

  # PATCH/PUT /types/1
  # PATCH/PUT /types/1.json
  def update
    respond_to do |format|
      if @type.update(type_params)
        format.html { redirect_to @type, notice: 'Type was successfully updated.' }
        format.js { render :show, status: :ok, location: @type }
      else
        format.html { render :edit }
        format.js { render json: @type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /types/1
  # DELETE /types/1.json
  def destroy
    @type.destroy
    respond_to do |format|
      format.html { redirect_to bookmarks_url, notice: 'Type was successfully destroyed.' }
      format.json { @type}
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_type
      @type = Type.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def type_params
      params.require(:type).permit(:theme, :link, :bookmark_id)
    end

    def select_bookmark
      @bookmark = Bookmark.all.pluck(:url, :id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/subcategories_helper.rb
module SubcategoriesHelper
end

app/helpers/types_helper.rb
module TypesHelper
end

app/views/bookmarks/_bookmark.html.erb
    <td><%= bookmark.url %></td>
    <td><%= bookmark.status %></td>
    
    <td><%= link_to 'Editar', edit_bookmark_path(bookmark), remote: true %></td>
    <td><%= link_to 'Borrar', bookmark, method: :delete, remote: true, data: { confirm: 'Are you sure?' } %></td>



  

        

app/views/bookmarks/_form.html.erb
<%= form_with(model: bookmark, remote: true, data: {confirm: '¿Estas Seguro?'}) do |form| %>
  <% if bookmark.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(bookmark.errors.count, "error") %> prohibited this bookmark from being saved:</h2>

      <ul>
      <% bookmark.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
    <%#= form.text_field :category, class:"input-group my-3", placeholder: 'Nombre' %>

    <%= form.text_field :url, class:"input-group my-3", placeholder: 'Link' %> 
  <div class="field">
    <%= form.select :status, Bookmark.statuses.keys %> 
  </div>
  
    <%= form.submit 'Guardar', class: "btn btn-info mb-5 btn-block", data: { disabled_with: 'Guardando...' } %>
<% end %>

app/views/bookmarks/_type.html.erb
        <% @bookmark.types.each do |type| %>
            <tr>
            <td><%= type.theme %></td>
            <td><%= type.link %></td>
            <td><%= link_to 'X', type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            <td><%= link_to 'Edit', edit_type_path(@type.id) %></td>
            
            <% end %>
     

app/views/bookmarks/create.js.erb
document.querySelector('#tbody').innerHTML += '<tr id="bookmark_<%=@bookmark.id%>"><%= j render @bookmark %></tr>'

app/views/bookmarks/destroy.js.erb
document.querySelector('#bookmark_<%= @bookmark.id %>').style.display = 'none';

app/views/bookmarks/edit.html.erb
<h1>Editing Bookmark</h1>

<%= render 'form', bookmark: @bookmark %>

<%= link_to 'Show', @bookmark %> |
<%= link_to 'Back', bookmarks_path %>

app/views/bookmarks/edit.js.erb
document.querySelector('#bookmark_<%= @bookmark.id %>').innerHTML = '<td colspan="2"><%= j render "form", bookmark: @bookmark %></td>';

app/views/bookmarks/index.html.erb
<div class="jumbotron bg-light">
        <h1 class="text-secondary">Creador de marcadores</h1>
        <%=link_to 'Nuevo Marcador (modo HTML)', new_bookmark_path, class: 'btn btn-info mx-5 my-5 text-white' %>
        <%= link_to  "Nuevo Tipo (Modo HTML)", new_category_path, class: 'btn btn-info mx-5 text-white' %>
        <%= link_to  "Categorias en formato JSON", get_api_path, class: 'btn btn-info mx-5 text-white' %>
</div>



<h2 style="margin-bottom:20px; margin-top:20px;">Crea tus marcadores (con Ajax)</h2>
<%= render 'form', bookmark: @bookmark%>

<%= search_form_for @q do |f| %>
  <div class="form-group">
    <%= f.label :status_eq, "Estado" %>
    <%= f.select :status_eq, options_for_select(Bookmark.statuses, @q.status_eq) {},{class: "form-control"} %>
  </div>
  <%= f.submit "Buscar por estado", class: "btn btn-primary" %>
<% end %>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Link</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody id="tbody" class="container">
    <div class="row">
      <div class="col-sm">
      <% @bookmarks.each do |bookmark| %>
        <tr id="bookmark_<%=bookmark.id%>">
          <%= render bookmark %>
        </tr>
      <% end %>
      </div>
    </div>
  </tbody>
</table>

  </tbody>

<%= column_chart @bookmarks_graphic %>
<%= pie_chart @types_graphic %>

<h2>Crea tu Categoria</h2>
<%= form_with(model: @category, url: create_category_path, method: :post, remote: true) do |form| %>

  <div class="field">
    <%= form.label :crear_categoria %>
    <%= form.text_field :name, class:"input-group", placeholder: 'Crea una categoria' %>
  </div>


  <div class="field">
    <%= form.label :elige_una_subcategoria %>
    <%= form.select :subcategory_id, options_for_select(@subcategories.pluck(:name, :id)), remote: true, prompt: 'Selecciona una subcategoria' %>
  </div>

  <div class="field">
    <%= form.label :elige_un_marcador %>
    <%= form.select :bookmark_id, options_for_select(@bookmarks.pluck(:url, :id)), remote: true, prompt: 'Selecciona un marcador' %>
  </div>

  <div class="field">
    <%= form.label :elige_un_tipo %>
    <%= form.select :kind_id, options_for_select(@kinds.pluck(:name, :id)), remote: true, prompt: 'Selecciona un tipo' %>
  </div>


  <div class="actions">
    <%= form.submit 'Guardar', class: "btn btn-info mb-5 btn-block" %>
  </div>
<% end %>

    <h2>Categorias / Subcategorias</h2>
    <%#= render @types %>
<%
=begin%>
 <% @types.each do |type| %>
  <tr>
    <% if type.bookmark.nil? %>
      <%= 'Marcador vacio' %>
    <% else %>
    
      <td><%= type.bookmark.category %></td>
    <% end %>
    <ul>
      <li><%= type.theme %></li>
      <li><%= type.link %></li>
      <td><%= link_to 'Editar', edit_type_path(type) %></td>
      <td><%= link_to 'Borrar', type, method: :delete, remote: true, data: { confirm: 'Are you sure?' } %></td>
    </ul>
  </tr>
<% end %> 
<%
=end%>

<div class="card-columns">
   <% @categories.reverse.each do |category| %>
     <div class="card bg-info text-white">
     <div class="card-body">
   <% if category.bookmark.nil? %>
      <h5 class="text-danger"><%= 'Marcador vacio / Sin Categoria' %></h5>
      <p class="text-danger"><%= 'Marcador sin Estado' %></p>
    <% else %>
          <h5 class="card-title text-white">Categoria: <%= category.name %></h5>
          <h6 class="card-title text-white">Marcador: <%= category.bookmark.url %></h6>
          <h6 class="card-title text-white">Estado: <%= category.bookmark.status %></h6>
    <% end %>
       <div class="card-block">
        <p class="card-text">Subcategoria: <%= category.subcategory.name %></p>
        <p class="card-text">Tipo: <%= category.kind.name %></p>
        <p class="card-text"><%#= category.link %></p>
        <span class="card-text text-white"><%= link_to 'Editar', edit_category_path(category) %></span>
        <span class="card-text text-white"><%= link_to 'Borrar', category, method: :delete, remote: true, data: { confirm: 'Are you sure?' } %></span>
       </div>
     </div>
    </div>
   <% end %>
</div>
<br><br><br>



<%#= render 'types/form', type: @type %>
</tbody>







      
        
       
        

app/views/bookmarks/new.html.erb
<h1>New Bookmark</h1>

<%= render 'form', bookmark: @bookmark %>

<%= link_to 'Back', bookmarks_path %>

app/views/bookmarks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Category:</strong>
  <%= @bookmark.category %>
</p>

<p>
  <strong>Url:</strong>
  <%= @bookmark.url %>
</p>

<%= link_to 'Edit', edit_bookmark_path(@bookmark) %> |
<%= link_to 'Back', bookmarks_path %>

app/views/bookmarks/update.js.erb
document.querySelector('#bookmark_<%= @bookmark.id %>').innerHTML = '<%= j render @bookmark %>'

app/views/categories/_category.html.erb
            <tr>
            <td><%= cat.subcategory %></td>
            <td><%#= cat.link %></td>
            <td><%= link_to 'X', cat, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            <td><%= link_to 'Edit', edit_category_path(cat.id) %></td>
            </tr>
            

app/views/categories/_form.html.erb
<%= form_with(model: category, remote: true) do |form| %>
  <%
=begin%>
 <% if type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(type.errors.count, "error") %> prohibited this type from being saved:</h2>

      <ul>
      <% type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
 
<%
=end%>
  <div class="field">
    <%= form.label :subcategory %>
    <%= form.text_field :subcategory %>
  </div>

  <div class="field">
    <%#= form.label :link %>
    <%#= form.text_field :link %>
  </div>

  <div class="field">
    <%= form.label :bookmark %>
    <%= form.select :bookmark_id, options_for_select(@bookmark), prompt: 'Selecciona un marcador' %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/create.js.erb
// document.querySelector('#type').innerHTML += '<%= @type.theme %>' +  '<%= @type.link %>'


var type_category = document.createTextNode('<%= @category.bookmark.url %>')
var category_theme = document.createTextNode('<%= @category.subcategory %>')
var category_link = document.createTextNode('<%= @category.link %>')
var li = document.createElement('li')

li.appendChild(category_subcategory)
li.appendChild(category_theme)
li.appendChild(category_link)
document.body.appendChild(li)

app/views/categories/destroy.js.erb
document.querySelector('#category_<%= @category.id %>').style.display = 'none';

app/views/categories/edit.html.erb
<h1>Editar Categoria</h1>

<%= render 'form', type: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Types</h1>

<table>
  <thead>
    <tr>
      <th>Theme</th>
      <th>Link</th>
      <th>Type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.theme %></td>
        <td><%= category.link %></td>
        <td><%= category.bookmark unless category.bookmark.nil? %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Type', new_type_path %>

app/views/categories/new.html.erb
<h1>New Type</h1>

<%= render 'form', type: @type %>

<%= link_to 'Marcadores', bookmarks_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Subcategoria:</strong>
  <%= @category.subcategory %>
</p>

<p>
  <strong>Link:</strong>
  <%= @category.bookmark.url %>
</p>

<p>
  <strong>Tipo:</strong>
  <%= @category.kind.name %>
</p>

<%= link_to 'Editar', edit_category_path(@category) %> |
<%= link_to  "Inicio", root_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Marcadores con Ajax</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,400;1,300&display=swap" rel="stylesheet">
  </head>

  <body class="body container">
    <%= yield %>
  </body>
</html>

app/views/types/_form.html.erb
<%= form_with(model: type, remote: true) do |form| %>
  <%
=begin%>
 <% if type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(type.errors.count, "error") %> prohibited this type from being saved:</h2>

      <ul>
      <% type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
 
<%
=end%>
  <div class="field">
    <%= form.label :theme %>
    <%= form.text_field :theme %>
  </div>

  <div class="field">
    <%= form.label :link %>
    <%= form.text_field :link %>
  </div>

  <div class="field">
    <%= form.label :bookmark %>
    <%= form.select :bookmark_id, options_for_select(@bookmark), prompt: 'Selecciona una categoria' %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>